# Generated by Django 5.1.6 on 2025-09-21 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="payment",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="review",
            old_name="review",
            new_name="id",
        ),
    ]
